version: '3.7'

services:
  db:
    restart: always
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    networks: 
      - backend
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_DB=${SQL_DATABASE}

  api:
    restart: always
    build: .
    command: python app/manage.py runserver 0.0.0.0:8000
    volumes:
     - .:/app
    ports:
      - "8000:8000"
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_HOST=${SQL_HOST}
      - SQL_PORT=${SQL_PORT}
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:

volumes:
  db-data: