# Generated by Django 2.2.1 on 2019-05-12 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=70)),
                ('imo_number', models.PositiveIntegerField(verbose_name='IMO Number')),
            ],
            options={
                'unique_together': {('name', 'imo_number')},
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('imo_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ships', to='ships.Ship')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
