# Generated by Django 2.2.1 on 2019-05-12 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('imo_number', 'date')},
        ),
    ]
