# Generated by Django 2.2.1 on 2019-05-09 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ship',
            unique_together={('name', 'imo_number')},
        ),
    ]
