# Generated by Django 2.2.1 on 2019-05-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0002_auto_20190512_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='imo_number',
            new_name='ship',
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('ship', 'date')},
        ),
    ]
