# Generated by Django 2.2.1 on 2019-05-12 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0003_auto_20190512_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='ships.Ship'),
        ),
    ]
