# Generated by Django 2.2.1 on 2019-05-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0003_auto_20190509_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('-date',)},
        ),
    ]
